name: 'dbt_migrations'
version: '1.0.0'
config-version: 2


require-dbt-version: ">=0.15.1"

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
